version: '3.9'

services:
    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_USER: ${MYSQL_USER:-myuser}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mypassword}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-mydatabase}
        volumes:
            - ../wp_backup/mysql:/var/lib/mysql:rw

    wordpress:
        image: wordpress:fpm
        restart: always
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-mysql}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-myuser}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-mypassword}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-mydatabase}
        volumes:
            - ../wp_backup/wordpress:/var/www/html
            - ./wordpress/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql

    nginx:
        image: nginx:stable
        restart: always
        ports:
           - '${NGINX_HOST_PORT_80}:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ../wp_backup/nginx/log:/var/log/nginx
            - ../wp_backup/wordpress:/var/www/html
        depends_on:
          - wordpress

# networks:
#     wp_network:
#         driver: bridge